### PR TITLE
Prepare for distribution

### PR DESCRIPTION
**Pull request by jitseniesen**
Last clean up before distribution: update readme and setup.py and unify copyright notices. Equivalent of spyder-ide/spyder-line-profiler#21.

### CODE REVIEW

**Comment by ccordoba12** [comment]
@goanpeca, do you also have reserved the name of this package in pypi?

**Comment by goanpeca** [comment]
@ccordoba12 and @jitseniesen yes I have that name reserved. Should I delete now so @jitseniesen can upload the package?

**Comment by jitseniesen** [comment]
@goanpeca Yes, please delete.

**Comment by goanpeca** [comment]
@jitseniesen done, all yours!

**Comment by goanpeca** [comment]
Could you add @goanpeca and @ccordoba12 as maintainers/developers of those packages :-) so we can upload in case of need?

**Comment by jitseniesen** [comment]
> Could you add @goanpeca and @ccordoba12 as maintainers/developers of those packages

You are both now maintainers of spyder-unittest, spyder-line-profiler and spyder-memory-profiler on PyPI

**Pull request merged**
